### ISSUE TITLE
Evaluate whether container solution could support all the hybrid cloud features

### ISSUE THREAD

**Issue by arthur-wangfeng** [Hybrid-Cloud/hybrid_cloud#10]
Evaluate whether container solution could support all the hybrid cloud features

due date

assignee: Eshed

**Comment by drormizrachi** [comment]
From Eshed:

I’ve updated the page with “supported by hypervm” column.
Bottom line – all features can be supported by (or regardless of) the technology, with the exception of “create image from VM” that has limitations (due to the need to convert from a regular VM to a container).

https://github.com/Hybrid-Cloud/hybrid_cloud/wiki/Hybrid-Cloud-Supported-Features
